export const Auth = {
  AUTH0_RETURN_TO_URL: process.env.AUTH0_RETURN_TO_URL!,
  AUTH0_CALLBACK_URL: process.env.AUTH0_CALLBACK_URL!,
  AUTH0_CLIENT_ID: process.env.AUTH0_CLIENT_ID!,
  AUTH0_CLIENT_SECRET: process.env.AUTH0_CLIENT_SECRET!,
  AUTH0_DOMAIN: process.env.AUTH0_DOMAIN!,
  AUTH0_LOGOUT_URL: process.env.AUTH0_LOGOUT_URL!,
  SECRETS: process.env.SECRETS!,
}
